/*
 * Copyright 2017 Abed Tony BenBrahim <tony.benrahim@10xdev.com>
 *     and Gwt-JElement project contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */


package com.tenxdev.jsinterop.generator.parsing.visitors.secondpass;

import com.tenxdev.jsinterop.generator.model.MethodArgument;
import com.tenxdev.jsinterop.generator.parsing.ParsingContext;
import org.antlr4.webidl.WebIDLParser;

import java.util.ArrayList;
import java.util.List;

class ConstructorArgumentsVisitor extends ContextWebIDLBaseVisitor<List<MethodArgument>> {

    public ConstructorArgumentsVisitor(ParsingContext parsingContext) {
        super(parsingContext);
    }

    @Override
    public List<MethodArgument> visitExtendedAttributeInner(WebIDLParser.ExtendedAttributeInnerContext ctx) {
        WebIDLParser.ExtendedAttributeInnerContext extendedAttributeInnerContext = ctx;
        List<MethodArgument> arguments = new ArrayList<>();
        List<String> tokens = new ArrayList<>();
        while (extendedAttributeInnerContext != null) {
            if (extendedAttributeInnerContext.otherOrComma() != null) {
                String token = extendedAttributeInnerContext.otherOrComma().getText();
                if (",".equals(token)) {
                    createArgument(tokens, arguments);
                    tokens.clear();
                } else {
                    tokens.add(token);
                }
                extendedAttributeInnerContext = extendedAttributeInnerContext.extendedAttributeInner(0);
            } else if (extendedAttributeInnerContext.extendedAttributeInner(0) != null) {
                StringBuilder type = new StringBuilder("");
                WebIDLParser.ExtendedAttributeInnerContext subContext = extendedAttributeInnerContext.extendedAttributeInner(0);
                while (subContext != null && subContext.otherOrComma() != null) {
                    String token = subContext.otherOrComma().getText();
                    type.append("or".equals(token) ? "|" : token);
                    subContext = subContext.extendedAttributeInner(0);
                }
                tokens.add(type.toString());
                extendedAttributeInnerContext = extendedAttributeInnerContext.extendedAttributeInner(1);
            } else {
                break;
            }
        }
        createArgument(tokens, arguments);
        return arguments;
    }

    private void createArgument(List<String> tokens, List<MethodArgument> arguments) {
        //This is ugly, but not as ugly as the parse tree generated by the grammar for extended attributes
        if (!tokens.isEmpty()) {
            boolean optional = false;
            if (tokens.remove("optional")) {
                optional = true;
            }
            tokens.remove("?");
            String defaultValue = null;
            int equalsIndex = tokens.indexOf("=");
            if (equalsIndex != -1) {
                defaultValue = tokens.get(equalsIndex + 1);
                tokens.remove(equalsIndex + 1);
                tokens.remove(equalsIndex);
            }

            String name = tokens.get(tokens.size() - 1);
            StringBuilder typeBuilder = new StringBuilder();
            for (int i = 0; i < tokens.size() - 1; ++i) {
                typeBuilder.append(tokens.get(i));
            }
            String type = removeOptionalIndicator(typeBuilder.toString());
            if (type.indexOf('|') != -1) {
                String[] types = type.split("\\|");
                arguments.add(new MethodArgument(name, parsingContext.getTypeFactory().getUnionType(types), false, optional, defaultValue, null));
            } else {
                arguments.add(new MethodArgument(name, parsingContext.getTypeFactory().getType(type),
                        false, optional, defaultValue, null));
            }
        }
    }

    private String removeOptionalIndicator(String type) {
        if (type.endsWith("?")) {
            return type.substring(0, type.length() - 1);
        }
        return type;
    }
}

